/**
 * citation-shared.ts — Shared citation types and pure helpers.
 *
 * Safe to import from both server and client code.
 * All heavy server-only logic (BibTeX parsing, Payload fetching) lives in citations.ts.
 */

export type CitationStyle =
  | "authoryear"
  | "apa"
  | "chicago"
  | "numeric"
  | "ieee"
  | "vancouver";

/** Styles that render [N] inline instead of (Author, Year) */
export const NUMERIC_STYLES: CitationStyle[] = ["numeric", "ieee", "vancouver"];

export function isNumericStyle(style: CitationStyle): boolean {
  return NUMERIC_STYLES.includes(style);
}

export interface ReferenceData {
  /** BibTeX cite key */
  key: string;
  /** Pre-formatted inline author-year: "(Corke et al., 2011)" */
  inlineAuthoryear: string;
  /** Full bibliography HTML generated by citation-js / CSL */
  bibliographyHtml: string;
  /** Extracted display title */
  title: string;
  /** Formatted authors string */
  authorsDisplay: string;
  /** Publication year */
  year: string;
  /** DOI without prefix, e.g. "10.1007/978-3-642-20144-8" */
  doi?: string;
  /** Arbitrary external URL */
  externalUrl?: string;
  /** Cover art URL (absolute or /media/…) */
  coverArtUrl?: string;
}
