import type {
  CollectionAfterChangeHook,
  CollectionAfterDeleteHook,
  Payload,
} from "payload";

// ---------------------------------------------------------------------------
// Scanners
// ---------------------------------------------------------------------------

/** Extract filenames from MDX text that reference /media/<filename> */
function extractMDXFilenames(content: string | null | undefined): Set<string> {
  if (!content) return new Set();
  const regex = /\/media\/([^"'\n\r>)#?]+)/g;
  const names = new Set<string>();
  let match: RegExpExecArray | null;
  while ((match = regex.exec(content)) !== null) {
    names.add(match[1].trim());
  }
  return names;
}

/** Recursively extract media document IDs from a Lexical JSON tree */
function extractLexicalMediaIds(lexicalData: unknown): Set<number | string> {
  const ids = new Set<number | string>();

  function traverse(node: unknown): void {
    if (!node || typeof node !== "object") return;
    const n = node as Record<string, unknown>;

    if (n.type === "upload" && n.relationTo === "media") {
      const value = n.value;
      if (typeof value === "string" || typeof value === "number") {
        ids.add(value);
      } else if (
        value &&
        typeof value === "object" &&
        "id" in (value as object)
      ) {
        ids.add((value as { id: number | string }).id);
      }
    }

    for (const key of ["children", "nodes"] as const) {
      if (Array.isArray(n[key])) {
        for (const child of n[key] as unknown[]) traverse(child);
      }
    }

    // Handle Lexical root wrapper: { root: { children: [...] } }
    if (n.root) traverse(n.root);
  }

  traverse(lexicalData);
  return ids;
}

// ---------------------------------------------------------------------------
// usedIn update helpers
// ---------------------------------------------------------------------------

type RefEntry = { relationTo: "modules" | "posts" | "tesselas"; value: string };

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type MediaWithUsedIn = { usedIn?: any[] };

function normalizeRef(ref: unknown): RefEntry | null {
  if (!ref || typeof ref !== "object") return null;
  const r = ref as Record<string, unknown>;
  if (
    r.relationTo !== "modules" &&
    r.relationTo !== "posts" &&
    r.relationTo !== "tesselas"
  )
    return null;
  const raw =
    r.value && typeof r.value === "object" && "id" in (r.value as object)
      ? (r.value as { id: unknown }).id
      : r.value;
  return {
    relationTo: r.relationTo as "modules" | "posts" | "tesselas",
    value: String(raw),
  };
}

async function updateMediaUsedIn(
  payload: Payload,
  mediaId: number | string,
  collectionSlug: "modules" | "posts" | "tesselas",
  docId: number | string,
  action: "add" | "remove",
): Promise<void> {
  try {
    // payload-types.ts is regenerated by Payload on first startup;
    // cast through unknown to handle the pre-regeneration stale types.
    const media = (await payload.findByID({
      collection: "media",
      id: mediaId,
      depth: 0,
      overrideAccess: true,
    })) as unknown as MediaWithUsedIn;
    if (!media) return;

    const docIdStr = String(docId);
    const current = (media.usedIn || [])
      .map(normalizeRef)
      .filter((r): r is RefEntry => r !== null);

    const exists = current.some(
      (r) => r.relationTo === collectionSlug && r.value === docIdStr,
    );

    let updated: RefEntry[];
    if (action === "add") {
      if (exists) return;
      updated = [...current, { relationTo: collectionSlug, value: docIdStr }];
    } else {
      if (!exists) return;
      updated = current.filter(
        (r) => !(r.relationTo === collectionSlug && r.value === docIdStr),
      );
    }

    await payload.update({
      collection: "media",
      id: mediaId,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      data: { usedIn: updated } as any,
      overrideAccess: true,
    });
  } catch (err) {
    console.error(
      `[syncMediaUsedIn] Failed to ${action} usedIn on media ${mediaId}:`,
      err,
    );
  }
}

// ---------------------------------------------------------------------------
// Module hooks  (MDX textarea → /media/<filename> pattern)
// ---------------------------------------------------------------------------

async function resolveMediaIdByFilename(
  payload: Payload,
  filename: string,
): Promise<number | string | undefined> {
  const result = await payload.find({
    collection: "media",
    where: { filename: { equals: filename } },
    depth: 0,
    limit: 1,
    overrideAccess: true,
  });
  return result.docs[0]?.id;
}

export const syncModuleMediaRefs: CollectionAfterChangeHook = async ({
  doc,
  previousDoc,
  req,
}) => {
  const { payload } = req;
  const oldFilenames = extractMDXFilenames(previousDoc?.content);
  const newFilenames = extractMDXFilenames(doc.content);

  const added = [...newFilenames].filter((f) => !oldFilenames.has(f));
  const removed = [...oldFilenames].filter((f) => !newFilenames.has(f));

  await Promise.all([
    ...added.map(async (filename) => {
      const id = await resolveMediaIdByFilename(payload, filename);
      if (id != null)
        await updateMediaUsedIn(payload, id, "modules", doc.id, "add");
    }),
    ...removed.map(async (filename) => {
      const id = await resolveMediaIdByFilename(payload, filename);
      if (id != null)
        await updateMediaUsedIn(payload, id, "modules", doc.id, "remove");
    }),
  ]);
};

export const cleanModuleMediaRefs: CollectionAfterDeleteHook = async ({
  doc,
  req,
}) => {
  const { payload } = req;
  const filenames = extractMDXFilenames(doc.content);

  await Promise.all(
    [...filenames].map(async (filename) => {
      const id = await resolveMediaIdByFilename(payload, filename);
      if (id != null)
        await updateMediaUsedIn(payload, id, "modules", doc.id, "remove");
    }),
  );
};

// ---------------------------------------------------------------------------
// Post hooks  (Lexical richText → upload nodes carry media IDs directly)
// ---------------------------------------------------------------------------

export const syncPostMediaRefs: CollectionAfterChangeHook = async ({
  doc,
  previousDoc,
  req,
}) => {
  const { payload } = req;
  const oldIds = extractLexicalMediaIds(previousDoc?.body);
  const newIds = extractLexicalMediaIds(doc.body);

  const added = [...newIds].filter((id) => !oldIds.has(id));
  const removed = [...oldIds].filter((id) => !newIds.has(id));

  await Promise.all([
    ...added.map((id) =>
      updateMediaUsedIn(payload, id, "posts", doc.id, "add"),
    ),
    ...removed.map((id) =>
      updateMediaUsedIn(payload, id, "posts", doc.id, "remove"),
    ),
  ]);
};

export const cleanPostMediaRefs: CollectionAfterDeleteHook = async ({
  doc,
  req,
}) => {
  const { payload } = req;
  const ids = extractLexicalMediaIds(doc.body);

  await Promise.all(
    [...ids].map((id) =>
      updateMediaUsedIn(payload, id, "posts", doc.id, "remove"),
    ),
  );
};

// ---------------------------------------------------------------------------
// Tessela hooks  (MDX textarea → /media/<filename> pattern)
// ---------------------------------------------------------------------------

export const syncTesselaMediaRefs: CollectionAfterChangeHook = async ({
  doc,
  previousDoc,
  req,
}) => {
  const { payload } = req;
  const oldFilenames = extractMDXFilenames(previousDoc?.content);
  const newFilenames = extractMDXFilenames(doc.content);

  const added = [...newFilenames].filter((f) => !oldFilenames.has(f));
  const removed = [...oldFilenames].filter((f) => !newFilenames.has(f));

  await Promise.all([
    ...added.map(async (filename) => {
      const id = await resolveMediaIdByFilename(payload, filename);
      if (id != null)
        await updateMediaUsedIn(payload, id, "tesselas", doc.id, "add");
    }),
    ...removed.map(async (filename) => {
      const id = await resolveMediaIdByFilename(payload, filename);
      if (id != null)
        await updateMediaUsedIn(payload, id, "tesselas", doc.id, "remove");
    }),
  ]);
};

export const cleanTesselaMediaRefs: CollectionAfterDeleteHook = async ({
  doc,
  req,
}) => {
  const { payload } = req;
  const filenames = extractMDXFilenames(doc.content);

  await Promise.all(
    [...filenames].map(async (filename) => {
      const id = await resolveMediaIdByFilename(payload, filename);
      if (id != null)
        await updateMediaUsedIn(payload, id, "tesselas", doc.id, "remove");
    }),
  );
};
