/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    courses: Course;
    modules: Module;
    tesselas: Tessela;
    offers: Offer;
    posts: Post;
    media: Media;
    activities: Activity;
    'student-groups': StudentGroup;
    scores: Score;
    references: Reference;
    'account-requests': AccountRequest;
    enrollments: Enrollment;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'modules' | 'tesselas' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    tesselas: TesselasSelect<false> | TesselasSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'student-groups': StudentGroupsSelect<false> | StudentGroupsSelect<true>;
    scores: ScoresSelect<false> | ScoresSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    'account-requests': AccountRequestsSelect<false> | AccountRequestsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'professor' | 'student';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Course code (e.g., PROJ-ROB)
   */
  code: string;
  title: string;
  /**
   * URL-friendly identifier (e.g., projetos-roboticos)
   */
  slug: string;
  /**
   * Brief course description
   */
  summary?: string | null;
  /**
   * Background image for the discipline card on /disciplinas
   */
  coverImage?: (number | null) | Media;
  workload?: {
    /**
     * Theoretical hours
     */
    theoretical?: number | null;
    /**
     * Practical hours
     */
    practical?: number | null;
  };
  /**
   * Default instructor for this course
   */
  instructor?: (number | null) | User;
  /**
   * When unchecked, this course is hidden from /disciplinas and all its links return 404.
   */
  visibility?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  /**
   * Auto-detected: content that references this file
   */
  usedIn?:
    | (
        | {
            relationTo: 'modules';
            value: number | Module;
          }
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'tesselas';
            value: number | Tessela;
          }
      )[]
    | null;
  _objectKey?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g., mt01-introducao)
   */
  slug: string;
  authors?: string | null;
  /**
   * Conteúdo MDX do módulo. Use a toolbar ou Ctrl+Espaço para inserir snippets.
   */
  content?: string | null;
  type: 'modulo-teorico' | 'modulo-pratico' | 'atividade-avaliativa' | 'recurso';
  /**
   * Parent course this module belongs to
   */
  course: number | Course;
  /**
   * Sort order within the course
   */
  order: number;
  /**
   * Controla se este módulo é listado na grade da disciplina.
   */
  visible?: boolean | null;
  /**
   * Habilita o acesso a este módulo através de sua URL direta, mesmo se não estiver visível.
   */
  linkable?: boolean | null;
  /**
   * Data de publicação do módulo.
   */
  publishedAt?: string | null;
  /**
   * Auto-managed by <CiteModule> usage in content. Do not edit manually.
   */
  relatedModules?: (number | Module)[] | null;
  /**
   * Auto-managed by <CiteTessela> usage in content. Do not edit manually.
   */
  relatedTesselas?: (number | Tessela)[] | null;
  /**
   * Citation style used when rendering <Cite /> components in this module. Affects both inline citations and the auto-generated References section.
   */
  citationStyle?: ('authoryear' | 'apa' | 'chicago' | 'numeric' | 'ieee' | 'vancouver') | null;
  /**
   * Auto-managed. Starting question numbers (per type) for this module within its course sequence. Updated on every publish.
   */
  questionOffsets?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tesselas de pesquisa, notas técnicas e estudos independentes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tesselas".
 */
export interface Tessela {
  id: number;
  title: string;
  /**
   * URL-friendly identifier used in /tesselas/[slug]
   */
  slug: string;
  authors?: string | null;
  /**
   * Conteúdo MDX da tessela. Use a toolbar ou Ctrl+Espaço para inserir snippets.
   */
  content?: string | null;
  /**
   * Plain text summary shown on listing cards.
   */
  abstract?: string | null;
  stage: 'rascunho' | 'em-andamento' | 'finalizado' | 'incrementando';
  /**
   * Controla se esta tessela é listada na página /tesselas e nos grafos.
   */
  visible?: boolean | null;
  /**
   * Habilita o acesso a esta tessela através de sua URL direta, mesmo se não estiver visível nas listagens.
   */
  linkable?: boolean | null;
  /**
   * Tags for filtering and graph clustering. Semicolon-separated, e.g. robotics; ai; slam
   */
  tags?: string | null;
  /**
   * Citation style used when rendering <Cite /> components in this tessela.
   */
  citationStyle?: ('authoryear' | 'apa' | 'chicago' | 'numeric' | 'ieee' | 'vancouver') | null;
  /**
   * Cover image shown on listing cards.
   */
  coverImage?: (number | null) | Media;
  /**
   * Free-text project label (e.g. "SLAM Robot", "Artigo IEEE 2026").
   */
  project?: string | null;
  /**
   * Manual publication date shown on cards and article header.
   */
  publishedAt?: string | null;
  /**
   * Courses related to this tessela.
   */
  relatedDisciplinas?: (number | Course)[] | null;
  /**
   * Auto-managed by <CiteModule> usage in content. Do not edit manually.
   */
  relatedModules?: (number | Module)[] | null;
  /**
   * Auto-managed by <CiteTessela> usage in content. Do not edit manually.
   */
  relatedTesselas?: (number | Tessela)[] | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'modules';
          value: number | Module;
        }
      | {
          relationTo?: 'tesselas';
          value: number | Tessela;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('modules' | 'tesselas' | 'media')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published';
  /**
   * Publication date
   */
  publishedAt?: string | null;
  /**
   * Optional: link to a specific offer for offer-scoped announcements. Leave empty for general news.
   */
  offer?: (number | null) | Offer;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  /**
   * Semester period (e.g., 2026.1, 2026.2)
   */
  period: string;
  status: 'active' | 'archived';
  /**
   * Which course this offer belongs to
   */
  course: number | Course;
  /**
   * Instructor for this specific offering
   */
  instructor?: (number | null) | User;
  /**
   * Students enrolled in this offer
   */
  students?: (number | User)[] | null;
  /**
   * The module the class is currently on. Controls synchronous progression for students.
   */
  currentModule?: (number | null) | Module;
  /**
   * Audit log tracking grading/activity changes
   */
  logs?:
    | {
        timestamp: string;
        action: string;
        details?: string | null;
        performedBy?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  /**
   * The offer this activity belongs to
   */
  offer: number | Offer;
  /**
   * Short identifier (e.g., AV, TF, P1)
   */
  acronym: string;
  /**
   * Full description (e.g., Avaliação Final, Trabalho Final)
   */
  description: string;
  /**
   * Points this activity is worth. The regular activities of an offer should sum to 10.0; extra ones come on top.
   */
  weight: number;
  /**
   * Graded: each student gets a percentage of the points. Checklist: the points are split across the tasks below, and a student earns the share of the tasks marked as done.
   */
  mode: 'graded' | 'checklist';
  /**
   * The tasks of a checklist activity. Each can be marked done per student.
   */
  tasks?:
    | {
        /**
         * Short acronym for the table heading (optional).
         */
        code?: string | null;
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Day the work is due (optional).
   */
  dueDate?: string | null;
  /**
   * Notes about this activity (optional).
   */
  comment?: string | null;
  /**
   * Regular activities add up to the semester's 10.0 points; extra ones are bonus points.
   */
  category: 'regular' | 'extra';
  /**
   * Whether this activity is graded per-student or per-group
   */
  type: 'individual' | 'group';
  /**
   * Display order within the offer
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-groups".
 */
export interface StudentGroup {
  id: number;
  /**
   * Group name (e.g., Grupo 1, Equipe Alpha)
   */
  name: string;
  offer: number | Offer;
  /**
   * Students assigned to this group
   */
  students?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores".
 */
export interface Score {
  id: number;
  offer: number | Offer;
  activity: number | Activity;
  /**
   * Whether this score is for an individual student or a group
   */
  entityType: 'student' | 'group';
  /**
   * The enrolled student this score belongs to (if entityType is student). Class lists come from SIGAA without user accounts, so scores point at the enrollment.
   */
  enrollment?: (number | null) | Enrollment;
  /**
   * The student (if entityType is student)
   */
  student?: (number | null) | User;
  /**
   * The group (if entityType is group)
   */
  group?: (number | null) | StudentGroup;
  /**
   * For a checklist activity: ids of the tasks this student has done. The percentage below is then their share of the activity's tasks.
   */
  completedTasks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Score from 0% to 100%
   */
  percentage: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  offer: number | Offer;
  /**
   * Matrícula: digits only, unique within the offer.
   */
  registration: string;
  name: string;
  /**
   * For a class split in two. Leave empty when the class is not split.
   */
  classGroup?: ('A' | 'B') | null;
  /**
   * The work group this student belongs to for the semester, if any. Pick a group of the same offer.
   */
  group?: (number | null) | StudentGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * Academic references. Paste the BibTeX entry; title/authors/year are auto-displayed for convenience.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  /**
   * BibTeX cite key (e.g. corke2011robotics). Must match exactly what you use in <Cite label="..." />.
   */
  key: string;
  /**
   * Full BibTeX entry. Example: @book{corke2011robotics, author = {Corke, Peter}, title = {Robotics, Vision and Control}, year = {2011}, publisher = {Springer} }
   */
  bibtex: string;
  /**
   * DOI (without the https://doi.org/ prefix). E.g. 10.1007/978-3-642-20144-8
   */
  doi?: string | null;
  /**
   * Optional direct URL (publisher page, arXiv, etc.)
   */
  externalUrl?: string | null;
  /**
   * Optional cover image (book cover, conference logo, etc.)
   */
  coverArt?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Requests sent from the site's user menu. Setting a request to Approved creates the user and e-mails them a link to set a password.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-requests".
 */
export interface AccountRequest {
  id: number;
  name: string;
  email: string;
  /**
   * Role the account is created with on approval. Change it before approving if needed.
   */
  requestedRole: 'student' | 'professor';
  /**
   * What the requester wrote (course, class, reason).
   */
  message?: string | null;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'tesselas';
        value: number | Tessela;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'student-groups';
        value: number | StudentGroup;
      } | null)
    | ({
        relationTo: 'scores';
        value: number | Score;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'account-requests';
        value: number | AccountRequest;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  slug?: T;
  summary?: T;
  coverImage?: T;
  workload?:
    | T
    | {
        theoretical?: T;
        practical?: T;
      };
  instructor?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  authors?: T;
  content?: T;
  type?: T;
  course?: T;
  order?: T;
  visible?: T;
  linkable?: T;
  publishedAt?: T;
  relatedModules?: T;
  relatedTesselas?: T;
  citationStyle?: T;
  questionOffsets?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tesselas_select".
 */
export interface TesselasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  authors?: T;
  content?: T;
  abstract?: T;
  stage?: T;
  visible?: T;
  linkable?: T;
  tags?: T;
  citationStyle?: T;
  coverImage?: T;
  project?: T;
  publishedAt?: T;
  relatedDisciplinas?: T;
  relatedModules?: T;
  relatedTesselas?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  period?: T;
  status?: T;
  course?: T;
  instructor?: T;
  students?: T;
  currentModule?: T;
  logs?:
    | T
    | {
        timestamp?: T;
        action?: T;
        details?: T;
        performedBy?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  offer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  usedIn?: T;
  _objectKey?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  offer?: T;
  acronym?: T;
  description?: T;
  weight?: T;
  mode?: T;
  tasks?:
    | T
    | {
        code?: T;
        name?: T;
        id?: T;
      };
  dueDate?: T;
  comment?: T;
  category?: T;
  type?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-groups_select".
 */
export interface StudentGroupsSelect<T extends boolean = true> {
  name?: T;
  offer?: T;
  students?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores_select".
 */
export interface ScoresSelect<T extends boolean = true> {
  offer?: T;
  activity?: T;
  entityType?: T;
  enrollment?: T;
  student?: T;
  group?: T;
  completedTasks?: T;
  percentage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  key?: T;
  bibtex?: T;
  doi?: T;
  externalUrl?: T;
  coverArt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-requests_select".
 */
export interface AccountRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  requestedRole?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  offer?: T;
  registration?: T;
  name?: T;
  classGroup?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}